import { useState } from "react";
import { useDocuments } from "../hooks/useDocuments";
import { 
  DocumentStatus, 
  GenerationType, 
  OutputFormat, 
  DocumentFilters 
} from "../types/document";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "../components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import { Badge } from "../components/ui/badge";
import { StatusBadge, PageState } from "../components/shared/StatusBadge";
import { 
  Search, 
  Filter, 
  RefreshCcw, 
  FileText,
  Clock,
  CheckCircle2,
  XCircle,
  Loader2,
  Download,
  ExternalLink
} from "lucide-react";
import { cn } from "../lib/utils";

export default function GeneratedDocuments() {
  const [filters, setFilters] = useState<DocumentFilters>({
    search: "",
    status: undefined,
    generationType: undefined,
    outputFormat: undefined,
  });

  const { data: documents, isLoading, isError, error, refetch } = useDocuments(filters);

  const handleFilterChange = (key: keyof DocumentFilters, value: string | undefined) => {
    setFilters((prev) => ({
      ...prev,
      [key]: value === "all" ? undefined : value,
    }));
  };

  const clearFilters = () => {
    setFilters({
      search: "",
      status: undefined,
      generationType: undefined,
      outputFormat: undefined,
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-gray-900">Generated Documents</h1>
          <p className="text-gray-500 mt-1 text-sm">Review and access documents generated by Cassatix.</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={() => refetch()}>
            <RefreshCcw className="mr-2 h-4 w-4" /> Refresh
          </Button>
        </div>
      </div>

      {/* Filters Bar */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center bg-white p-4 rounded-xl border shadow-sm">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
          <Input
            placeholder="Search by Case ID or Template..."
            className="pl-9 bg-gray-50/50 border-gray-200 focus:bg-white transition-colors"
            value={filters.search}
            onChange={(e) => handleFilterChange("search", e.target.value)}
          />
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex items-center gap-2 text-sm text-gray-500 mr-2">
            <Filter className="h-4 w-4" />
            <span>Filters:</span>
          </div>
          
          <Select
            value={filters.status || "all"}
            onValueChange={(v) => handleFilterChange("status", v as DocumentStatus)}
          >
            <SelectTrigger className="w-[130px] h-9 text-xs bg-gray-50/50 border-gray-200">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              <SelectItem value={DocumentStatus.QUEUED}>Queued</SelectItem>
              <SelectItem value={DocumentStatus.PROCESSING}>Processing</SelectItem>
              <SelectItem value={DocumentStatus.COMPLETED}>Completed</SelectItem>
              <SelectItem value={DocumentStatus.FAILED}>Failed</SelectItem>
            </SelectContent>
          </Select>

          <Select
            value={filters.generationType || "all"}
            onValueChange={(v) => handleFilterChange("generationType", v as GenerationType)}
          >
            <SelectTrigger className="w-[130px] h-9 text-xs bg-gray-50/50 border-gray-200">
              <SelectValue placeholder="Type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Types</SelectItem>
              <SelectItem value={GenerationType.PREVIEW}>Preview</SelectItem>
              <SelectItem value={GenerationType.FINAL}>Final</SelectItem>
            </SelectContent>
          </Select>

          <Select
            value={filters.outputFormat || "all"}
            onValueChange={(v) => handleFilterChange("outputFormat", v as OutputFormat)}
          >
            <SelectTrigger className="w-[130px] h-9 text-xs bg-gray-50/50 border-gray-200">
              <SelectValue placeholder="Format" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Formats</SelectItem>
              <SelectItem value={OutputFormat.DOCX}>DOCX</SelectItem>
              <SelectItem value={OutputFormat.PDF}>PDF</SelectItem>
            </SelectContent>
          </Select>

          {(filters.search || filters.status || filters.generationType || filters.outputFormat) && (
            <Button variant="ghost" size="sm" onClick={clearFilters} className="text-xs text-gray-500 h-9">
              Clear
            </Button>
          )}
        </div>
      </div>

      {/* Content Area */}
      <div className="bg-white rounded-xl border shadow-sm overflow-hidden min-h-[400px]">
        {isLoading ? (
          <PageState 
            title="Loading documents..." 
            icon="loading" 
            className="min-h-[400px]"
          />
        ) : isError ? (
          <PageState 
            title="Failed to load documents" 
            description={error instanceof Error ? error.message : "An unexpected error occurred while fetching documents."}
            icon="error"
            action={<Button variant="outline" onClick={() => refetch()}>Try Again</Button>}
            className="min-h-[400px]"
          />
        ) : documents && documents.length > 0 ? (
          <Table>
            <TableHeader className="bg-gray-50/50">
              <TableRow>
                <TableHead className="w-[250px] text-xs font-semibold uppercase tracking-wider text-gray-500">Document / Template</TableHead>
                <TableHead className="text-xs font-semibold uppercase tracking-wider text-gray-500">Case ID</TableHead>
                <TableHead className="text-xs font-semibold uppercase tracking-wider text-gray-500">Type</TableHead>
                <TableHead className="text-xs font-semibold uppercase tracking-wider text-gray-500">Format</TableHead>
                <TableHead className="text-xs font-semibold uppercase tracking-wider text-gray-500">Status</TableHead>
                <TableHead className="text-xs font-semibold uppercase tracking-wider text-gray-500">Generated At</TableHead>
                <TableHead className="text-right"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {documents.map((doc) => (
                <TableRow 
                  key={doc.id} 
                  className="group hover:bg-gray-50/80 transition-colors"
                >
                  <TableCell className="py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded bg-gray-100 flex items-center justify-center text-gray-500 group-hover:bg-white group-hover:shadow-sm transition-all">
                        <FileText className="h-4 w-4" />
                      </div>
                      <div>
                        <div className="font-medium text-gray-900">{doc.template?.name || "Unknown Template"}</div>
                        <div className="text-[10px] text-gray-400 font-mono mt-0.5 uppercase tracking-tighter">
                          {doc.template?.code || "N/A"}
                        </div>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <span className="text-sm font-medium text-gray-700">{doc.caseId}</span>
                  </TableCell>
                  <TableCell>
                    <StatusBadge status={doc.generationType} type="generation" />
                  </TableCell>
                  <TableCell>
                    <span className="text-xs font-semibold text-gray-500">{doc.outputFormat}</span>
                  </TableCell>
                  <TableCell>
                    <StatusBadge status={doc.status} type="document" showIcon />
                  </TableCell>
                  <TableCell>
                    <div className="flex flex-col">
                      <span className="text-xs text-gray-700">{new Date(doc.createdAt).toLocaleDateString()}</span>
                      <span className="text-[10px] text-gray-400">{new Date(doc.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                    </div>
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      {doc.status === DocumentStatus.COMPLETED && doc.storagePath && (
                        <>
                          <Button variant="ghost" size="icon" className="h-8 w-8 text-gray-400 hover:text-gray-900" asChild title="Download Document">
                            <a href={`/api/documents/${doc.id}/download`} target="_blank" rel="noreferrer">
                              <Download className="h-4 w-4" />
                            </a>
                          </Button>
                          <Button variant="ghost" size="icon" className="h-8 w-8 text-gray-400 hover:text-gray-900" title="View Details">
                            <ExternalLink className="h-4 w-4" />
                          </Button>
                        </>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <PageState 
            title="No documents found"
            description={filters.search || filters.status || filters.generationType || filters.outputFormat
              ? "Try adjusting your filters to find what you're looking for."
              : "Documents generated by Cassatix will appear here."}
            icon="empty"
            action={(filters.search || filters.status || filters.generationType || filters.outputFormat) && (
              <Button variant="outline" onClick={clearFilters}>Clear All Filters</Button>
            )}
            className="min-h-[400px]"
          />
        )}
      </div>
    </div>
  );
}
